Wait until the database is reachable in job-create-site (#207)
* Wait until the database is reachable in job-create-site

* Add annotations to job-create-site

* Fix the annotations iteration in job-create-site

* Don't consider "site already exists" as an error in job-create-site.yaml

* Fix syntax errors in job-create-site.yaml

* Fix syntax errors in job-create-site.yaml

* Enable debugging in job-create-site.yaml

* Remove redundant semi-colon in job-create-site.yaml

* Change SITE_NAME variable usage job-create-site.yaml

* Change parentheses to curly braces in bench output in job-create-site.yaml

* Remove unneeded stderr forward in job-create-site.yaml

* Fix syntax error in job-create-site.yaml

* Forward bench new-site output to variable and stdout in job-create-site.yaml

* Forward output of bench new-site through tee to cat in job-create-site.yaml

* Forward bench new-site to /dev/tty in job-create-site.yaml

* Redirect output to stderr job-create-site.yaml

diff --git a/erpnext/templates/job-create-site.yaml b/erpnext/templates/job-create-site.yaml
--- a/erpnext/templates/job-create-site.yaml
+++ b/erpnext/templates/job-create-site.yaml
@@ -5,6 +5,12 @@ metadata:
   name: {{ template "erpnext.fullname" . }}-new-site-{{ now | date "20060102150405" }}
   labels:
     {{- include "erpnext.labels" . | nindent 4 }}
+  annotations:
+{{- with .Values.jobs.createSite.annotations }}
+{{- range $key, $value := . }}
+    {{ $key }}: {{ $value | quote }}
+{{- end }}
+{{- end }}
 spec:
   backoffLimit: {{ .Values.jobs.createSite.backoffLimit }}
   template:
@@ -36,6 +42,33 @@ spec:
                 fi
               done;
               echo "sites/common_site_config.json found";
+
+              echo "Waiting for database to be reachable...";
+              wait-for-it -t 180 $(DB_HOST):$(DB_PORT);
+              echo "Database is reachable.";
+          env:
+            - name: "DB_HOST"
+              {{- if .Values.postgresql.host }}
+              value: {{ .Values.postgresql.host }}
+              {{- else if .Values.postgresql.enabled }}
+              value: {{ .Release.Name }}-postgresql
+              {{- else if .Values.mariadb.enabled }}
+              {{- if eq .Values.mariadb.architecture "replication" }}
+              value: {{ .Release.Name }}-mariadb-primary
+              {{- else }}
+              value: {{ .Release.Name }}-mariadb
+              {{- end }}
+              {{- else }}
+              value: "{{ .Values.dbHost }}"
+              {{- end }}
+            - name: "DB_PORT"
+              {{- if .Values.dbPort }}
+              value: {{ .Values.dbPort | quote }}
+              {{- else if .Values.postgresql.enabled }}
+              value: {{ .Values.postgresql.primary.service.ports.postgresql | quote }}
+              {{- else }}
+              value: {{ .Values.mariadb.primary.service.ports.mysql | quote }}
+              {{- end }}
           resources:
             {{- toYaml .Values.jobs.createSite.resources | nindent 12 }}
           securityContext:
@@ -50,23 +83,41 @@ spec:
         command: ["bash", "-c"]
         args:
           - >
-            bench new-site $(SITE_NAME)
-            --no-mariadb-socket
-            --db-type=$(DB_TYPE)
-            --db-host=$(DB_HOST)
-            --db-port=$(DB_PORT)
-            --admin-password=$(ADMIN_PASSWORD)
-            --mariadb-root-username=$(DB_ROOT_USER)
-            --mariadb-root-password=$(DB_ROOT_PASSWORD)
-        {{- if .Values.jobs.createSite.installApps }}
-          {{- range .Values.jobs.createSite.installApps }}
-            --install-app={{ . }}
-          {{- end }}
-        {{- end }}
-          {{- if .Values.jobs.createSite.forceCreate }}
-            --force
-          {{- end }}
-            ;rm -f currentsite.txt
+            set -x;
+
+            bench_output=$(bench new-site ${SITE_NAME} \
+              --no-mariadb-socket \
+              --db-type=${DB_TYPE} \
+              --db-host=${DB_HOST} \
+              --db-port=${DB_PORT} \
+              --admin-password=${ADMIN_PASSWORD} \
+              --mariadb-root-username=${DB_ROOT_USER} \
+              --mariadb-root-password=${DB_ROOT_PASSWORD} \
+            {{- if .Values.jobs.createSite.installApps }}
+              {{- range .Values.jobs.createSite.installApps }}
+              --install-app={{ . }} \
+              {{- end }}
+            {{- end }}
+            {{- if .Values.jobs.createSite.forceCreate }}
+              --force \
+            {{- end }}
+             | tee /dev/stderr);
+
+            bench_exit_status=$?;
+
+            if [ $bench_exit_status -ne 0 ]; then
+                # Don't consider the case "site already exists" an error.
+                if [[ $bench_output == *"already exists"* ]]; then
+                    echo "Site already exists, continuing...";
+                else
+                    echo "An error occurred in bench new-site: $bench_output"
+                    exit $bench_exit_status;
+                fi
+            fi
+ 
+            set -e;
+
+            rm -f currentsite.txt
         env:
           - name: "SITE_NAME"
             value: "{{ .Values.jobs.createSite.siteName }}"
